# Generated by Django 3.2 on 2021-04-17 16:53

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20210417_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.db.models.fields.PositiveIntegerField]),
        ),
    ]
